// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsCpsU5mo2IGaWJSqjsZeA2c5nEId9FYI',
    appId: '1:12290137766:web:338b24ea1a4356bf1e5e67',
    messagingSenderId: '12290137766',
    projectId: 'travelapp-912f0',
    authDomain: 'travelapp-912f0.firebaseapp.com',
    storageBucket: 'travelapp-912f0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAofzab6m4-_vEZNeYmhgj2HPwu7WYrZkg',
    appId: '1:12290137766:android:34740e3de5819c341e5e67',
    messagingSenderId: '12290137766',
    projectId: 'travelapp-912f0',
    storageBucket: 'travelapp-912f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwc_f4IL8BxwqkUl6pPhYPbyiRsxIUvsE',
    appId: '1:12290137766:ios:2e4944762569a9b21e5e67',
    messagingSenderId: '12290137766',
    projectId: 'travelapp-912f0',
    storageBucket: 'travelapp-912f0.firebasestorage.app',
    iosBundleId: 'com.example.travelApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwc_f4IL8BxwqkUl6pPhYPbyiRsxIUvsE',
    appId: '1:12290137766:ios:2e4944762569a9b21e5e67',
    messagingSenderId: '12290137766',
    projectId: 'travelapp-912f0',
    storageBucket: 'travelapp-912f0.firebasestorage.app',
    iosBundleId: 'com.example.travelApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsCpsU5mo2IGaWJSqjsZeA2c5nEId9FYI',
    appId: '1:12290137766:web:d8f8e882f6f9013b1e5e67',
    messagingSenderId: '12290137766',
    projectId: 'travelapp-912f0',
    authDomain: 'travelapp-912f0.firebaseapp.com',
    storageBucket: 'travelapp-912f0.firebasestorage.app',
  );

}